version: '3.3'

services:

   # https://hub.docker.com/_/nginx
   nginx:
       image: nginx:latest
       container_name: "${PROJECT_NAME}_nginx"
       ports:
         - "${NGINX_PORT}:80"
       working_dir: /var/www/html
       volumes:
         - ./docker/etc/nginx:/etc/nginx/conf.d
         - ./logs/nginx:/var/log/nginx
         - ./app:/var/www/html
       environment:
          - NGINX_HOST=${NGINX_HOST}
       command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/wordpress.template > /etc/nginx/conf.d/wordpress.conf && nginx -g 'daemon off;'"
       links:
         - wordpress
       restart: always

   # https://hub.docker.com/_/mysql
   db:
     image: mysql:${MYSQL_TAG}

     # For MySQL 8.0
     #image: mysql:8
     #command: '--default-authentication-plugin=mysql_native_password'

     container_name: "${PROJECT_NAME}_db"
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     restart: always

   # https://hub.docker.com/_/wordpress
   wordpress:
     image: wordpress:${WP_VERSION}-php${PHP_VERSION}-fpm
     container_name: "${PROJECT_NAME}_wordpress"
     environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
       - WORDPRESS_DB_USER=${MYSQL_USER}
       - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
     working_dir: /var/www/html
     volumes:
       - ./app:/var/www/html
       #- ./app/wp-content:/var/www/html/wp-content
       - ./docker/etc/php-fpm/custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
     #depends_on:
     #  - db
     links:
       - db
     restart: always

   wordpress-cli:
       image: wordpress:cli
       container_name: "${PROJECT_NAME}_wordpress_cli"
       volumes:
         - ./app:/var/www/html
         - ./docker/etc/php-fpm/custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
       depends_on:
         - db
         - wordpress

   # https://hub.docker.com/r/phpmyadmin/phpmyadmin
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: "${PROJECT_NAME}_phpmyadmin"
      ports:
          - "${PMA_PORT}:80"
      environment:
          PMA_HOST: db
      depends_on:
        - db

   # @todo services
   # jwilder/nginx-proxy
   # composer
   # mailhog
   # redis
   # https / letsencrypt
   # blackfire

volumes:
    db_data: