version: '3.3'

services:

   # https://hub.docker.com/_/nginx
   # Doesn't play well with wordpress fpm based images
#   nginx:
#       image: nginx:latest
#       container_name: "${PROJECT_NAME}_nginx"
#       ports:
#         - "${NGINX_HTTP_PORT}:80"
#       working_dir: /var/www/html
#       volumes:
#         - ./docker/etc/nginx:/etc/nginx/conf.d
#         - ./logs/nginx:/var/log/nginx
#         - ./app:/var/www/html
#       environment:
#          - NGINX_HOST=${NGINX_HOST}
#       #command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/wordpress.conf > /etc/nginx/conf.d/wordpress.conf && nginx -g 'daemon off;'"
#       links:
#         - wordpress
#       restart: always

   # https://hub.docker.com/r/jwilder/nginx-proxy
   nginx-proxy:
     image: jwilder/nginx-proxy
     container_name: "${PROJECT_NAME}_nginx-proxy"
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro

   # https://hub.docker.com/_/mysql
   mysql:
     image: mysql:${MYSQL_TAG}

     # For MySQL 8.0
     #image: mysql:8
     #command: '--default-authentication-plugin=mysql_native_password'

     container_name: "${PROJECT_NAME}_mysql"
     ports:
           - "${MYSQL_PORT}:3306"
     volumes:
       - ./data/mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     restart: always

   # https://hub.docker.com/_/wordpress
   wordpress:
     # -fpm or apache, unfortunately fpm doesn't work properly with nginx-proxy
     image: wordpress:${WP_VERSION}-php${PHP_VERSION}-apache
     container_name: "${PROJECT_NAME}_wordpress"
     environment:
       - VIRTUAL_HOST=${WP_HTTP_HOST}
       - WORDPRESS_DB_HOST=mysql:3306
       - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
       - WORDPRESS_DB_USER=${MYSQL_USER}
       - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
     working_dir: /var/www/html
     volumes:
       - ./app:/var/www/html
       #- ./app/wp-content:/var/www/html/wp-content
       - ./docker/etc/php-fpm/custom.ini:/usr/local/etc/php/conf.d/999-custom.ini
     #depends_on:
     #  - mysql
     ports:
       - "${WP_HTTP_PORT}:80"
     expose:
       - ${WP_HTTP_PORT}
     links:
       - mysql
     restart: always

   wordpress-cli:
       image: wordpress:cli
       container_name: "${PROJECT_NAME}_wordpress_cli"
       user: xfs
       command: >
         /bin/sh -c '
         sleep 10;
         wp core install --path="/var/www/html" --url="http://${WP_HTTP_HOST}" --title="Dockerized Wordpress" --admin_user=${WP_ADMIN_USER} --admin_password=${WP_ADMIN_PASS} --admin_email=${WP_ADMIN_EMAIL};
         curl http://loripsum.net/api/4 | wp post generate --post_content --count=10'
       depends_on:
         - wordpress
         - mysql
       volumes:
         - ./app:/var/www/html

   # https://hub.docker.com/r/phpmyadmin/phpmyadmin
   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: "${PROJECT_NAME}_phpmyadmin"
      ports:
          - "${PMA_PORT}:80"
      expose:
          - ${PMA_PORT}
      environment:
          VIRTUAL_HOST: ${PMA_HTTP_HOST}
          PMA_HOST: mysql
      depends_on:
        - mysql

   # @todo services
   # jwilder/nginx-proxy
   # https / letsencrypt
   # composer
   # mailhog
   # redis
   # phpredisadmin
   # blackfire

networks:
    default:
      external:
        name: nginx-proxy