version: '3.3'

services:
   nginx:
       image: nginx:latest
       container_name: "${PROJECT_NAME}_nginx"
       #env_file: ./docker/.env @todo
       ports:
         - "${NGINX_PORT}:80"
       working_dir: /var/www/html
       volumes:
         - ./docker/etc/nginx:/etc/nginx/conf.d
         - ./logs/nginx:/var/log/nginx
         - ./app:/var/www/html
       links:
         - wordpress
       restart: always

   db:
     image: mysql:${MYSQL_TAG}
     #image: mysql:8
     #command: '--default-authentication-plugin=mysql_native_password'
     container_name: "${PROJECT_NAME}_db"
     #env_file: ./docker/.env @todo
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     restart: always

   wordpress:
     #@todo custom build so that we can configure Nginx + PHP + WP CLI
     #Available tags on https://hub.docker.com/_/wordpress?tab=tags
     image: wordpress:${WP_VERSION}-php${PHP_VERSION}-fpm
     container_name: "${PROJECT_NAME}_wordpress"
     #env_file: ./docker/.env @todo
     ##ports:
     ##  - "${PORT}:80"
     environment:
       - WORDPRESS_DB_HOST=db:3306
       - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
       - WORDPRESS_DB_USER=${MYSQL_USER}
       - WORDPRESS_DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
       #- WORDPRESS_DB_PREFIX=${MYSQL_PREFIX}
       #- WORDPRESS_TABLE_PREFIX=wp_
       #- WORDPRESS_THEME=${THEME_NAME}
     working_dir: /var/www/html
     volumes:
       - ./app:/var/www/html
       #- ./app/wp-content:/var/www/html/wp-content
       - ./docker/etc/php-fpm/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
     #depends_on:
     #  - db
     links:
       - db
     restart: always

volumes:
    db_data: